racecar:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  left_direction_controller:
    type: effort_controllers/JointVelocityController
    joint: left_steering_hinge_joint
    pid: {p: 500.0, i: 50.0, d: 0.0}

  right_direction_controller:
    type: effort_controllers/JointVelocityController
    joint: right_steering_hinge_joint
    pid: {p: 500.0, i: 50.0, d: 0.0}
  
  right_rear_controller:
    type: effort_controllers/JointVelocityController
    joint: right_rear_wheel_joint
    pid: {p: 500.0, i: 50.0, d: 0.0}
  
  left_rear_controller:
    type: effort_controllers/JointVelocityController
    joint: right_upper_wheel_joint
    pid: {p: 500.0, i: 50.0, d: 0.0}

